# Generated by Selenium IDE

from selenium import webdriver
from selenium.webdriver.common.by import By


class TestAddgroup():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_addgroup(self):
    self.Open_home_page()
    self.Login()
    self.Open_group_page()
    self.Creat_group()
    self.logout()

  def logout(self):
    # Logout
    self.driver.find_element(By.LINK_TEXT, "Logout").click()

  def Creat_group(self):
    # Creat group
    self.driver.find_element(By.NAME, "new").click()
    self.driver.find_element(By.ID, "content").click()
    self.driver.find_element(By.NAME, "group_name").click()
    self.driver.find_element(By.NAME, "group_name").send_keys("sdf")
    self.driver.find_element(By.NAME, "group_header").click()
    self.driver.find_element(By.NAME, "group_header").send_keys("sdf")
    self.driver.find_element(By.NAME, "group_footer").click()
    self.driver.find_element(By.NAME, "group_footer").send_keys("sdf")
    self.driver.find_element(By.NAME, "submit").click()

  def Open_group_page(self):
    # Open group page
    self.driver.find_element(By.LINK_TEXT, "groups").click()

  def Login(self):
    # Login
    self.driver.find_element(By.NAME, "user").click()
    self.driver.find_element(By.NAME, "user").send_keys("admin")
    self.driver.find_element(By.NAME, "pass").click()
    self.driver.find_element(By.NAME, "pass").send_keys("secret")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(7)").click()

  def Open_home_page(self):
    # Open home page
    self.driver.get("http://localhost/addressbook/")
    self.driver.set_window_size(550, 692)
  
