# Generated by Selenium IDE

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains


class TestAddcontact():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_addcontact(self):
    self.Open_home_page()
    self.Login()
    self.Add_contact()
    self.Logout()

  def Logout(self):
    # Logout
    self.driver.find_element(By.LINK_TEXT, "Logout").click()

  def Add_contact(self):
    # Add new contact
    self.driver.find_element(By.LINK_TEXT, "add new").click()
    self.driver.find_element(By.NAME, "firstname").click()
    self.driver.find_element(By.NAME, "firstname").send_keys("123")
    self.driver.find_element(By.NAME, "middlename").send_keys("123")
    self.driver.find_element(By.NAME, "lastname").send_keys("123")
    self.driver.find_element(By.NAME, "nickname").send_keys("123")
    self.driver.find_element(By.NAME, "title").send_keys("123")
    self.driver.find_element(By.NAME, "company").send_keys("123")
    self.driver.find_element(By.NAME, "address").send_keys("123")
    self.driver.find_element(By.NAME, "home").send_keys("123")
    self.driver.find_element(By.NAME, "mobile").send_keys("123")
    self.driver.find_element(By.NAME, "work").send_keys("123")
    self.driver.find_element(By.NAME, "fax").send_keys("123")
    self.driver.find_element(By.NAME, "email").send_keys("123")
    self.driver.find_element(By.NAME, "email2").send_keys("123")
    self.driver.find_element(By.NAME, "email3").send_keys("123")
    self.driver.find_element(By.NAME, "homepage").send_keys("123")
    self.driver.find_element(By.NAME, "bday").click()
    dropdown = self.driver.find_element(By.NAME, "bday")
    dropdown.find_element(By.XPATH, "//option[. = '14']").click()
    self.driver.find_element(By.CSS_SELECTOR, "select:nth-child(61) > option:nth-child(16)").click()
    dropdown = self.driver.find_element(By.NAME, "bmonth")
    dropdown.find_element(By.XPATH, "//option[. = 'November']").click()
    self.driver.find_element(By.CSS_SELECTOR, "select:nth-child(62) > option:nth-child(12)").click()
    self.driver.find_element(By.NAME, "byear").click()
    self.driver.find_element(By.NAME, "byear").click()
    self.driver.find_element(By.NAME, "byear").send_keys("1992")
    self.driver.find_element(By.NAME, "aday").click()
    dropdown = self.driver.find_element(By.NAME, "aday")
    dropdown.find_element(By.XPATH, "//option[. = '13']").click()
    self.driver.find_element(By.CSS_SELECTOR, "select:nth-child(66) > option:nth-child(15)").click()
    self.driver.find_element(By.NAME, "bmonth").click()
    self.driver.find_element(By.NAME, "amonth").click()
    dropdown = self.driver.find_element(By.NAME, "amonth")
    dropdown.find_element(By.XPATH, "//option[. = 'December']").click()
    self.driver.find_element(By.CSS_SELECTOR, "select:nth-child(67) > option:nth-child(13)").click()
    self.driver.find_element(By.NAME, "ayear").click()
    self.driver.find_element(By.NAME, "ayear").click()
    element = self.driver.find_element(By.NAME, "ayear")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.NAME, "ayear").click()
    self.driver.find_element(By.NAME, "ayear").click()
    element = self.driver.find_element(By.NAME, "ayear")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.NAME, "ayear").send_keys("1993")
    self.driver.find_element(By.NAME, "address2").click()
    self.driver.find_element(By.NAME, "address2").send_keys("123")
    self.driver.find_element(By.NAME, "phone2").click()
    self.driver.find_element(By.NAME, "phone2").send_keys("123")
    self.driver.find_element(By.NAME, "notes").click()
    self.driver.find_element(By.NAME, "notes").send_keys("123")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(87)").click()

  def Login(self):
    # Login
    self.driver.find_element(By.NAME, "user").click()
    self.driver.find_element(By.NAME, "user").send_keys("admin")
    self.driver.find_element(By.NAME, "pass").click()
    self.driver.find_element(By.NAME, "pass").send_keys("secret")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(7)").click()

  def Open_home_page(self):
    # Open home page
    self.driver.get("http://localhost/addressbook/")
  
